[build]
default-target = "x86_64-unknown-linux-musl"
pre-build = ["apt -y update && apt install -y protobuf-compiler"]

[target.x86_64-pc-windows-msvc]
image = "ghcr.io/cross-rs/x86_64-pc-windows-msvc-cross:local"
